apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: main-api-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main-api
          image: zelenushechka/main-api:20250528222019
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: AUX_SERVICE_URL
              value: "http://auxiliary-service.devops-app.svc.cluster.local:8001"
