apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-api
  namespace: argocd
spec:
  project: default
  destination:
    namespace: main-api-ns
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/zelenushechka/devops-way.git
    path: kubernetes/main-api
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
