apiVersion: v1
kind: Service
metadata:
  name: auxiliary-service
  namespace: auxiliary-service-ns
spec:
  selector:
    app: auxiliary
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
