apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auxiliary-service
  namespace: argocd
spec:
  project: default
  destination:
    namespace: auxiliary-service-ns
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/zelenushechka/devops-way.git
    path: kubernetes/auxiliary-service
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
