FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn boto3

COPY auxiliary_service.py .

EXPOSE 8001

CMD ["uvicorn", "auxiliary_service:app", "--host", "0.0.0.0", "--port", "8001"]
