version: '3.8'

services:
  auxiliary:
    build:
      context: .
      dockerfile: Dockerfile.auxiliary
    ports:
      - "8001:8001"
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=ASIA4HWCNZM62AUAOJUD
      - AWS_SECRET_ACCESS_KEY=TvO5/qmB5Kadl060HbK+PKQawelWFsZvPqHZcf4U

  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "8000:8000"
    environment:
      # Ensure the Main API uses the auxiliary container by its service name
      - AUX_SERVICE_URL=http://auxiliary:8001
