FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENV AUX_SERVICE_URL=http://auxiliary:8001

CMD ["uvicorn", "main_api:app", "--host", "0.0.0.0", "--port", "8000"]
