apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliary-service
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auxiliary
  template:
    metadata:
      labels:
        app: auxiliary
    spec:
      containers:
        - name: auxiliary-service
          image: zelenushechka/auxiliary-service:20250528221440
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
