apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: devops-app
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTRIV0NOWk02V0dCRFJWWEg=
  AWS_SECRET_ACCESS_KEY: WWNiT3Fwc09zeFFQOGpzVW9xc2F1SGdBaFI0ZmNaQmtpdTdLQlhYUQ==
