apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: devops-app
spec:
  selector:
    app: main
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
