apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main-api
          image: main-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: AUX_SERVICE_URL
              value: "http://auxiliary-service.devops-app.svc.cluster.local:8001"
