name: Build & Deploy

on: workflow_dispatch

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Image Tags
        id: tag
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push Main API Image
        run: |
          cd app
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/main-api:${IMAGE_TAG} -f Dockerfile.main .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/main-api:${IMAGE_TAG}

      - name: Build & Push Auxiliary Service Image
        run: |
          cd app
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/auxiliary-service:${IMAGE_TAG} -f Dockerfile.auxiliary .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auxiliary-service:${IMAGE_TAG}

  update-k8s-files:
    name: Update Kubernetes Deployments & Commit Changes
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Deployment YAML Files
        run: |
          cd kubernetes
          IMAGE_TAG="${{ needs.build-and-push.outputs.image_tag }}"
          sed -i "s|image: zelenushechka/main-api:.*|image: zelenushechka/main-api:${IMAGE_TAG}|" main-deployment.yaml
          sed -i "s|image: zelenushechka/auxiliary-service:.*|image: zelenushechka/auxiliary-service:${IMAGE_TAG}|" auxiliary-deployment.yaml
          
      - name: Commit & Push Updates
        run: |
          IMAGE_TAG="${{ needs.build-and-push.outputs.image_tag }}"
          cd kubernetes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add main-deployment.yaml auxiliary-deployment.yaml
          git commit -m "Bumped service versions to ${IMAGE_TAG}"
          git push origin main

  authenticate-aws:
    name: Authenticate with AWS using GitHub OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Verify AWS Authentication
        run: aws sts get-caller-identity
